name: HTML to PDF
description: Github Action to print HTML files to PDF format using Puppeteer
author: Southrop
inputs:
  input:
    description: Comma separated list of paths/URLs to print
    required: true
  outputPath:
    description: Desired path in the repo for the printed PDF to be added to
    required: false
    default: 'output.pdf'
  pageOptions:
    description: Comma separated list of JSON options to be passed to Puppeteer to be used for specific pages
    required: false
    default: ''
  globalOptions:
    description: JSON options to be passed to Puppeteer to be used for all pages
    required: false
    default: '{}'
runs:
  using: docker
  image: Dockerfile
branding:
  color: red
  icon: file-text