name: HTML to PDF
description: Github Action to print HTML files to PDF format using Puppeteer
author: Southrop
inputs:
  inputPaths:
    description: A comma separated list of paths of the HTML files to print
    required: true
  outputPath:
    description: The desired path in the repo for the resultant PDF to be added to
    required: false
    default: 'output.pdf'
  puppeteerOptions:
    description: JSON options to be passed directly to Puppeteer
    required: false
    default: '{}'
runs:
  using: 'node14'
  main: 'dist/index.js'
branding:
  color: red
  icon: file-text