on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test this action
    steps:
    - uses: actions/checkout@v2
    - uses: southrop/html-to-pdf-action@main
      with:
        input: 'https://github.com/explore,example/index.html,example/about/index.html'
        outputPath: print.pdf
        pageOptions: ',{"format": "Letter"}'
        globalOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - uses: actions/upload-artifact@v2
      with:
        name: Output
        path: print.pdf