on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test this action
    steps:
    - uses: southrop/html-to-pdf-action@master
      with:
        inputPaths: 'index.html,about/index.html'
        outputPath: pdf/print.pdf
        puppeteerOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
