on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test this action
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci && sudo apt-get install xvfb
    - uses: southrop/html-to-pdf-action@main
      with:
        inputPaths: 'index.html,about/index.html'
        outputPath: pdf/print.pdf
        puppeteerOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - uses: actions/upload-artifact@v2
      with:
        name: Output
        path: pdf/print.pdf